theme: just-the-docs

# If issues with merging of this file occur in the future, please run the following command in a terminal:
# git config merge.ours.driver true 
baseurl: /Digital-Interfaces/test  # For test branch: /repository-name/test

#theme: just-the-docs 
title: Digital Interfaces
color_scheme: digital-interfaces
plugins:
  - jekyll-redirect-from
  - jekyll-tabs
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: note
    color: blue
  attention:
    title: attention
    color: yellow

# External navigation links
nav_external_links:
  - title: Connected Interaction Kit
    url: https://id-studiolab.github.io/Connected-Interaction-Kit
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: DI Brightspace
    url: https://brightspace.tudelft.nl/d2l/home/681612
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Hedy - Python learning
    url: https://hedy.org/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: W3Schools - Python
    url: https://www.w3schools.com/python/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: CircuitPython Docs
    url: https://docs.circuitpython.org/en/latest/README.html
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Chat Bot - DI Helpdesk
    url: https://poe.com/DI_assitant_bot
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab